<?php

return [
    'announcement' => env('STOREFRONT_ANNOUNCEMENT', 'Free shipping on orders over $150'),

    'contact' => [
        'to_address' => env('CONTACT_FORM_TO_ADDRESS', env('MAIL_FROM_ADDRESS', 'hello@example.com')),
        'to_name' => env('CONTACT_FORM_TO_NAME', env('APP_NAME', 'Lunar Store')),
        'display_email' => env('STOREFRONT_CONTACT_EMAIL', 'online@popattack.com.au'),
        'online_email' => env('STOREFRONT_ONLINE_EMAIL', 'online@popattack.com.au'),
        'partnerships_email' => env('STOREFRONT_PARTNERSHIPS_EMAIL', 'partnerships@popattack.com.au'),
        'display_phone' => env('STOREFRONT_CONTACT_PHONE'),
    ],

    'mapbox' => [
        'token' => env('MAPBOX_TOKEN', 'pk.eyJ1IjoidmVuZGFibGVzIiwiYSI6ImNtZHNycWcxazBoZm4ya29ubnR6ZGY4NWkifQ.db2JuRNjd7tcV1YLTjAmIg'),
        'style_light' => env('MAPBOX_STYLE_LIGHT', 'mapbox://styles/mapbox/streets-v12'),
        'style_dark' => env('MAPBOX_STYLE_DARK', 'mapbox://styles/mapbox/dark-v11'),
    ],

    'stock_locator_url' => env('STOREFRONT_STOCK_LOCATOR_URL'),
    'legacy_stock_locator_url' => env('STOREFRONT_LEGACY_STOCK_LOCATOR_URL', 'https://popattack.com.au/stock-locator/'),

    'locations' => [
        [
            'id' => 'world-square-sydney',
            'name' => 'World Square Shopping Centre',
            'location' => 'Sydney CBD',
            'address' => '644 George St, Sydney NSW 2000, Australia',
            'latitude' => -33.87750,
            'longitude' => 151.20667,
            'description' => 'Our World Square location brings Pop Attack into the heart of Sydney with around-the-clock access and frequent stock updates.',
            'status' => 'Open',
            'hours' => [
                'monday' => 'Open 24 hours',
                'tuesday' => 'Open 24 hours',
                'wednesday' => 'Open 24 hours',
                'thursday' => 'Open 24 hours',
                'friday' => 'Open 24 hours',
                'saturday' => 'Open 24 hours',
                'sunday' => 'Open 24 hours',
            ],
            'products' => [
                'Pokemon',
                'Magic: The Gathering',
                'Yu-Gi-Oh!',
                'Digimon',
                'Dragon Ball Super',
                'Sports Cards',
            ],
            'features' => [
                '24/7 access',
                'Real-time stock finder support',
                'Collector-friendly CBD location',
            ],
        ],
    ],

    'stock_locator_demo' => [
        [
            'id' => 'stock-001',
            'location_id' => 'world-square-sydney',
            'location' => 'World Square Shopping Centre',
            'suburb' => 'Sydney CBD',
            'category' => 'Pokemon',
            'product' => 'Pokemon TCG: Scarlet & Violet Booster Bundle',
            'sku' => 'PKM-SV-BUNDLE-001',
            'price' => '$49.95',
            'stock_level' => 18,
            'stock_status' => 'In Stock',
            'status' => 'Active',
            'updated_at' => 'Updated 12 mins ago',
        ],
        [
            'id' => 'stock-002',
            'location_id' => 'world-square-sydney',
            'location' => 'World Square Shopping Centre',
            'suburb' => 'Sydney CBD',
            'category' => 'Pokemon',
            'product' => 'Pokemon 151 Elite Trainer Box',
            'sku' => 'PKM-151-ETB-002',
            'price' => '$129.95',
            'stock_level' => 4,
            'stock_status' => 'Low Stock',
            'status' => 'Active',
            'updated_at' => 'Updated 21 mins ago',
        ],
        [
            'id' => 'stock-003',
            'location_id' => 'world-square-sydney',
            'location' => 'World Square Shopping Centre',
            'suburb' => 'Sydney CBD',
            'category' => 'Magic: The Gathering',
            'product' => 'Magic Foundations Play Booster Box',
            'sku' => 'MTG-FDN-PLAY-003',
            'price' => '$239.95',
            'stock_level' => 9,
            'stock_status' => 'In Stock',
            'status' => 'Active',
            'updated_at' => 'Updated 35 mins ago',
        ],
        [
            'id' => 'stock-004',
            'location_id' => 'world-square-sydney',
            'location' => 'World Square Shopping Centre',
            'suburb' => 'Sydney CBD',
            'category' => 'Yu-Gi-Oh!',
            'product' => 'Quarter Century Bonanza Booster Pack',
            'sku' => 'YGO-QCB-004',
            'price' => '$9.95',
            'stock_level' => 27,
            'stock_status' => 'In Stock',
            'status' => 'Active',
            'updated_at' => 'Updated 42 mins ago',
        ],
        [
            'id' => 'stock-005',
            'location_id' => 'world-square-sydney',
            'location' => 'World Square Shopping Centre',
            'suburb' => 'Sydney CBD',
            'category' => 'Digimon',
            'product' => 'Digimon Special Booster Box',
            'sku' => 'DIGI-SPB-005',
            'price' => '$89.95',
            'stock_level' => 0,
            'stock_status' => 'Out of Stock',
            'status' => 'Active',
            'updated_at' => 'Updated 1 hour ago',
        ],
        [
            'id' => 'stock-006',
            'location_id' => 'world-square-sydney',
            'location' => 'World Square Shopping Centre',
            'suburb' => 'Sydney CBD',
            'category' => 'Sports Cards',
            'product' => '2025 NBA Donruss Fat Pack',
            'sku' => 'NBA-DON-006',
            'price' => '$14.95',
            'stock_level' => 11,
            'stock_status' => 'In Stock',
            'status' => 'Active',
            'updated_at' => 'Updated 1 hour ago',
        ],
    ],

    'shipping' => [
        'standard_rate' => (int) env('STOREFRONT_STANDARD_SHIPPING_RATE', 995),
        'express_rate' => (int) env('STOREFRONT_EXPRESS_SHIPPING_RATE', 1995),
        'free_over' => (int) env('STOREFRONT_FREE_SHIPPING_OVER', 15000),
    ],
];
